### ISSUE TITLE
Rajouter un emoji pour plus de granularité ? 

### ISSUE THREAD

**Issue by soizicpenicaud** [entrepreneur-interet-general/ma-semaine#12]
J'aime beaucoup l'idée des emoji. Je rajouterais un emoji " :) " (à la droite du " :|" et à la gauche du " :D ", pour que l'on sache quand les équipes sont juste "contentes" et quand elles ont eu une très bonne semaine.

**Comment by AntoineAugusti** [comment]
Hey @soizicpenicaud.

You want to add another spirit to have a balance between 😐 and 😀. I've added 🙂 in between these two.

Thanks for your suggestion!
