### ISSUE TITLE
Apporter des précisions dans les différents champs sur les actions dont on peut parler 

### ISSUE THREAD

**Issue by soizicpenicaud** [entrepreneur-interet-general/ma-semaine#13]
L'année dernière, Bastien avait établi des catégories dans lesquelles pouvaient tomber les actions rapportées en standup. Peut-être serait-il intéressant d'en préciser certaines pour "inspirer" les équipes ?  

Pour rappel, les voici :
[A]pprentissage
[C]ommunication (interne et externe)
[D]onnées (recherche, accès, compréhension)
[I]nstallation (physique et informatique)
[M]anagement (réunions, gestion de projet)
[P]roduction (code, données, doc, etc.)
[S]ervices informatiques (rendus à l’administration)
[T]ransformation de la culture informatique
[U]tilisateur (entretiens, retours, UX, UI)

Il y a probablement de la synthèse à faire. Par exemple, la catégorie "installation" pourrait être supprimée, et la catégorie "transformation de la culture informatique" pourrait être reformulée.

**Comment by AntoineAugusti** [comment]
What's your point of view on this @jbledevehat?

**Comment by jbledevehat** [comment]
If we want to keep the tool simple, I do not think it's a good idea to add categories.

**Comment by AntoineAugusti** [comment]
Agreed. Closing for now.
