### ISSUE TITLE
Préciser les réponses à apporter à la catégorie "Notre besoin"

### ISSUE THREAD

**Issue by soizicpenicaud** [entrepreneur-interet-general/ma-semaine#14]
J'ai vu que vous aviez reformulé le champ "Demande d'aide" en "notre besoin". Les formulations sont similaires, mais elles impliquent potentiellement 2 utilisateurs différents : 
- "Demande d'aide" implique que ce soit une demande faite à la promotion (ce qui justifie qu'elle soit envoyée dans ce standup). 
- "Besoin" peut être aussi réflexif (par ex : "nous avons besoin de clarifier notre organisation interne"). 

La question est donc : quelles infos souhaiterions-nous avoir ? 

Pour moi, les deux sont pertinentes. Proposition : on peut suggérer les deux dans le champ (sous forme d'exemple), et ainsi orienter les différents types de besoins à exprimer.

**Comment by AntoineAugusti** [comment]
Done in https://github.com/entrepreneur-interet-general/ma-semaine/commit/8ced7b110d24a16a1ce1f87c17937aa6712105cc
