### ISSUE TITLE
Mode "brouillon" si les EIG sont en asynchrone pour remplir le formulaire

### ISSUE THREAD

**Issue by guenolec** [entrepreneur-interet-general/ma-semaine#22]
Serait-il possible de créer une espèce de mode brouillon, un formulaire pré-rempli si les EIG (je pense notamment aux groupes de 3) souhaite remplir le formulaire en asynchrone ?

**Comment by AntoineAugusti** [comment]
Hello @guenolec,

You're asking to have a kind of draft mode in case people want to collaborate and write together. We don't even have the notion of "users" right now and will likely not introduce one to keep it simple. People can use other tools if they want to coordinate on this.

If the need arises, we can reconsider this later.
