### ISSUE TITLE
Préciser le principe dans "à propos"

### ISSUE THREAD

**Issue by milkosofi** [entrepreneur-interet-general/ma-semaine#24]
Le paragraphe sur "le principe" commence par une explication de ce qu'est "un stand-up" et donc ce que l'outil ma semaine n'est pas. J'ai l'impression que ça vaudrait le coup de plus marquer la différence entre le "stand-up" et l'outil Ma semaine : 
- prendre un parti sur la façon dont on dénomme l'outil - "Ma semaine" par exemple ;
- dans le deuxième paragraphe du principe mettre "au lieu d'interrompre le travail de tout le monde, l'outil ma semaine permet..."

Petit point chipotage : si on met "stand-up" en italique dans le paragraphe "principe", autant mettre le "stand-up mettings" du paragraphe "pourquoi cet outil" en italique aussi.

**Comment by AntoineAugusti** [comment]
We haven't decided a name yet, once #18 is resolved, we will stick the name multiple times in this page.

I've improved how standup meetings is written in https://github.com/entrepreneur-interet-general/ma-semaine/commit/7487246314691732784564ad1a6996d87727be77
