### ISSUE TITLE
Le CR envoyé par email est pessimiste par défaut

### ISSUE THREAD

**Issue by bzg** [entrepreneur-interet-general/ma-semaine#27]
Bonjour, le CR envoyé par email contient cette phrase à la fin:

> Malheureusement, nous n'avons pas de nouvelles pour ces projets : 😢.

... sans qu'aucun projet ne soit listé, car tous on répondu. Peut-être prévoir le cas où tout le monde répond ?

**Comment by AntoineAugusti** [comment]
Hey Bastien,

You're reporting a case when a sentence is added even when everyone has filed a report. It was a bug and it was fixed in https://github.com/entrepreneur-interet-general/ma-semaine/commit/2ceb6e486a48607fc97203dd6ad78ddcdb395a12. Thanks!

**Comment by bzg** [comment]
Heya, switching to english now. Thanks for the fix!

**Comment by bzg** [comment]
Seen, it makes sense, thanks!
