### ISSUE TITLE
Utiliser "défi" plutôt que "projet" ?

### ISSUE THREAD

**Issue by bzg** [entrepreneur-interet-general/ma-semaine#28]
Hello, je ne sais pas si cela a déjà fait l'objet d'une discussion dans l'équipe EIG - l'email hebdomadaire utilise "projet" au lieu de "défi". Plutôt utiliser le même vocabulaire que sur le site ?

**Comment by AntoineAugusti** [comment]
Hey Bastien,

You're asking about why we don't use wording specific to the EIG program. See my previous answer: https://github.com/entrepreneur-interet-general/ma-semaine/issues/25#issuecomment-470033234
