### ISSUE TITLE
Supprimer une phrase du mail si la totalité a saisie

### ISSUE THREAD

**Issue by jbledevehat** [entrepreneur-interet-general/ma-semaine#35]
Supprimer cette phrase dans le mail "Malheureusement, nous n'avons pas de nouvelles pour ces projets : 😢." si tous les projets ont été saisis.

**Comment by AntoineAugusti** [comment]
Fixed, duplicate of https://github.com/entrepreneur-interet-general/ma-semaine/issues/27
