### ISSUE TITLE
Typo correction on the front page

### ISSUE THREAD

**Issue by guenolec** [entrepreneur-interet-general/ma-semaine#41]
The front page states that the answers are "300 caractères par champ — l'équivalent de 2 tweets.".

I think a typo correction could be applied as, since a Twitter update, tweet lenght are now of 280 symbols.

**Comment by AntoineAugusti** [comment]
Hey @guenolec,

Thanks for your question. This sentence was used to give a rough idea of the expected length of the content. The real limit is 300 characters per field https://github.com/entrepreneur-interet-general/ma-semaine/blob/c203f6a91141d07ba7e0cc4e7214faacc8a45912/app/Http/Controllers/ReportsController.php#L20. Mentioning 2 tweets is just here to help, even if it's actually 20 characters less as you noted.

I've updated the wording in https://github.com/entrepreneur-interet-general/ma-semaine/commit/dd7dbb55c4e5b39f94d7b8624e1e5dea3ea06102.

**Comment by AntoineAugusti** [comment]
Fix of the fix https://github.com/entrepreneur-interet-general/ma-semaine/commit/efbb6728280b26b049f25915c5d28f150cc41739
