### ISSUE TITLE
White square on GH logo on footer

### ISSUE THREAD

**Issue by SebastienTouze** [entrepreneur-interet-general/ma-semaine#45]
Reproduce : on the main page, put cursor hover the the Github logo on footer

Expected : no white square

This is in fact the same behavior than in menu on header with text but not suitable for a white logo. 
This may be more related to the template than ma-semaine though

**Comment by AntoineAugusti** [comment]
Yep, it's an upstream issue that will be fixed in the new release of  https://github.com/etalab/template.data.gouv.fr. I'll update it when it's released.

**Comment by AntoineAugusti** [comment]
Fixed in https://github.com/entrepreneur-interet-general/ma-semaine/commit/ff65e617fcabc850462e0d862b7523247ec8b539
