### ISSUE TITLE
Update the projet logo size in the weekly report send by email

### ISSUE THREAD

**Issue by guenolec** [entrepreneur-interet-general/ma-semaine#48]
There seems to be an issue with the logo size send in the weekly report by email. 

The logo appears on the right size on the website version, but much larger on the email version.

**Comment by AntoineAugusti** [comment]
Can you send me a screenshot and information about your operating system and email client?

**Comment by AntoineAugusti** [comment]
My side
![](https://puu.sh/D0o0z/7d7f1e152a.png)

**Comment by guenolec** [comment]
I'm using Outlook 2013 and this is what comes up 

![image](https://user-images.githubusercontent.com/46894478/54445027-3f7cc300-4744-11e9-9b65-962f47d93db7.png)

**Comment by AntoineAugusti** [comment]
Tired of Microsoft issues... I'll take a look at it, thanks

**Comment by AntoineAugusti** [comment]
I think we should leave the `px` off for some odd reasons in Outlook. This should do the trick. If you can post a message to confirm later @guenolec, that'd be great.

Closing for now.

**Comment by guenolec** [comment]
The bug was fixed in the latest version sent
